language: node_js

node_js:
  - '14'
  - '15'

os:
  - windows

before_install:
  # https://travis-ci.community/t/command-npm-i-g-npm-latest-fails/431/7
  - node `npm prefix -g`/node_modules/npm/bin/npm-cli.js i -g npm@7
